"""
Initial

Revision ID: 16eb3d1ccd28
Revises: 
Create Date: 2025-11-13 22:36:01.571161
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16eb3d1ccd28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """
    Upgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    """
    Downgrade schema.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###